#!/usr/bin/env bash
# Create a Moodle dev environment for one version (4.1 … 5.2): an app + db compose stack under
# $MOODLE_ENVS/<ver> (default ~/moodle-envs) joined to the shared mailhog + selenium stack.
# Usage: install.sh <version> [pgsql|mysql] [--src <path>] [--php X.Y] [--host <name-or-ip>] [--https] [--phpunit] [--behat]
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
ROOT="${MOODLE_ENVS:-$HOME/moodle-envs}"
DBPASS='m@0dl3ing'
ADMINPASS='Admin1234!'

usage() {
    sed -n '2,4p' "$0" | sed 's/^# \{0,1\}//' >&2
    exit 1
}

ver="${1:-}"; [ -n "$ver" ] || usage; shift
dbtype=pgsql; src=""; php=""; host=""; https=0; init_phpunit=0; init_behat=0
while [ $# -gt 0 ]; do
    case "$1" in
        pgsql|mysql) dbtype="$1" ;;
        --src) [ $# -ge 2 ] || usage; src="$(cd "$2" && pwd)"; shift ;;
        --php) [ $# -ge 2 ] || usage; php="$2"; shift ;;
        --host) [ $# -ge 2 ] || usage; host="$2"; shift ;;
        --https) https=1 ;;
        --phpunit) init_phpunit=1 ;;
        --behat) init_behat=1 ;;
        *) usage ;;
    esac
    shift
done

# Moodle version -> branch, highest supported PHP, minimum supported DB majors (release notes).
case "$ver" in
    4.1) branch=MOODLE_401_STABLE; phpdef=8.1; pg=13; my=8.0 ;;
    4.2) branch=MOODLE_402_STABLE; phpdef=8.2; pg=13; my=8.0 ;;
    4.3) branch=MOODLE_403_STABLE; phpdef=8.2; pg=13; my=8.0 ;;
    4.4) branch=MOODLE_404_STABLE; phpdef=8.3; pg=13; my=8.0 ;;
    4.5) branch=MOODLE_405_STABLE; phpdef=8.3; pg=13; my=8.0 ;;
    5.0) branch=MOODLE_500_STABLE; phpdef=8.4; pg=14; my=8.4 ;;
    5.1) branch=MOODLE_501_STABLE; phpdef=8.4; pg=15; my=8.4 ;;
    5.2) branch=MOODLE_502_STABLE; phpdef=8.4; pg=16; my=8.4 ;;
    *) echo "Unsupported Moodle version '$ver' (4.1 … 5.2)" >&2; exit 1 ;;
esac
php="${php:-$phpdef}"
mm="${ver/./}"
name="moodle$mm"
env="$ROOT/$ver"
compose="$env/docker-compose.yml"
webport="80$mm"
wwwroot="http://$name.localhost"; [ -z "$host" ] || wwwroot="http://$host:$webport"
tlsport="84$mm"
if [ "$https" = 1 ]; then
    [ -n "$host" ] || { echo "--https needs --host <tailnet name>" >&2; exit 1; }
    tlsroot="https://$host:$tlsport"
fi
code="${src:-$env/www}"
mount="${src:-./www}"
case "$ver" in 5.1|5.2) web="public/"; docroot="/var/www/html/public" ;; *) web=""; docroot="/var/www/html" ;; esac
if [ "$dbtype" = pgsql ]; then
    dbimage="postgres:$pg"; dbport="54$mm"; dbinner=5432; cfgdbtype=pgsql; dbextra=""
else
    dbimage="mysql:$my"; dbport="33$mm"; dbinner=3306; cfgdbtype=mysqli; dbextra=", 'dbcollation' => 'utf8mb4_bin'"
fi

echo "== shared stack (mailhog + selenium)"
mkdir -p "$ROOT/shared"
[ -f "$ROOT/shared/docker-compose.yml" ] || cp -p "$HERE/docker-compose.shared.yml" "$ROOT/shared/docker-compose.yml"
[ -f "$ROOT/shared/nginx.conf" ] || cp -p "$HERE/nginx.conf" "$ROOT/shared/nginx.conf"
docker compose -f "$ROOT/shared/docker-compose.yml" up -d

echo "== environment $name at $env"
mkdir -p "$env/moodledata" "$env/phpunitdata" "$env/behatdata" "$env/behatfaildumps"
chmod 777 "$env/moodledata" "$env/phpunitdata" "$env/behatdata" "$env/behatfaildumps"
if [ ! -f "$code/version.php" ] && [ ! -f "$code/public/version.php" ]; then
    [ -n "$src" ] && { echo "No Moodle checkout at $src" >&2; exit 1; }
    rm -rf "$code"
    git -c http.version=HTTP/1.1 clone --branch "$branch" --depth 1 https://github.com/moodle/moodle.git "$code"
fi

if [ "$dbtype" = pgsql ]; then
    dbblock="    image: $dbimage
    environment:
      POSTGRES_USER: moodle
      POSTGRES_PASSWORD: \"$DBPASS\"
      POSTGRES_DB: moodle
    volumes:
      - dbdata:/var/lib/postgresql/data"
else
    dbblock="    image: $dbimage
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --skip-log-bin
    environment:
      MYSQL_ROOT_PASSWORD: \"$DBPASS\"
      MYSQL_USER: moodle
      MYSQL_PASSWORD: \"$DBPASS\"
      MYSQL_DATABASE: moodle
    volumes:
      - dbdata:/var/lib/mysql"
fi
cat > "$compose" <<EOF
# Moodle $ver dev environment, generated by /moodle-install. Mailhog + selenium are shared and
# live in ../shared. Start with: docker compose up -d   (services restart unless-stopped after a reboot)
name: $name
services:
  db:
    restart: unless-stopped
$dbblock
    ports:
      - "$dbport:$dbinner"
  app:
    restart: unless-stopped
    image: moodlehq/moodle-php-apache:$php
    depends_on:
      - db
    ports:
      - "$webport:80"
    environment:
      APACHE_DOCUMENT_ROOT: $docroot
    volumes:
      - $mount:/var/www/html
      - ./moodledata:/var/www/moodledata
      - ./phpunitdata:/var/www/phpunitdata
      - ./behatdata:/var/www/behatdata
      - ./behatfaildumps:/var/www/behatfaildumps
    networks:
      default:
      moodle-shared:
        aliases:
          - $name
volumes:
  dbdata:
networks:
  moodle-shared:
    external: true
EOF
docker compose -f "$compose" up -d

echo "== waiting for db"
for _ in $(seq 1 60); do
    if [ "$dbtype" = pgsql ]; then
        docker compose -f "$compose" exec -T db pg_isready -h 127.0.0.1 -U moodle -q && break
    else
        docker compose -f "$compose" exec -T db mysqladmin ping -h127.0.0.1 -umoodle -p"$DBPASS" --silent 2>/dev/null && break
    fi
    sleep 2
done

if [ "$https" = 1 ]; then
    tlsnote="// Follow the request host, so LAN IP, localhost and the tailnet name all work; TLS is
// terminated by \`tailscale serve\` on port $tlsport. CLI and cron keep the URL above."
else
    tlsnote="// Follow the request host, so LAN IP, localhost and any other name all work.
// CLI and cron keep the URL above."
fi
wwwrootcfg="\$CFG->wwwroot   = '$wwwroot';
$tlsnote
if (!empty(\$_SERVER['HTTP_HOST'])) {
    if (!empty(\$_SERVER['HTTP_X_FORWARDED_PROTO']) && \$_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https') {
        \$CFG->wwwroot = 'https://' . \$_SERVER['HTTP_HOST'];
        \$CFG->sslproxy = true;
    } else {
        \$CFG->wwwroot = 'http://' . \$_SERVER['HTTP_HOST'];
    }
}"

cfg="$code/config.php"
if [ -f "$cfg" ]; then
    echo "config.php exists, kept as is (check dbhost=db and wwwroot=$wwwroot)"
else
    cat > "$cfg" <<EOF
<?php  // Moodle configuration file, generated by /moodle-install.
unset(\$CFG);
global \$CFG;
\$CFG = new stdClass();

\$CFG->dbtype    = '$cfgdbtype';
\$CFG->dblibrary = 'native';
\$CFG->dbhost    = 'db';
\$CFG->dbname    = 'moodle';
\$CFG->dbuser    = 'moodle';
\$CFG->dbpass    = '$DBPASS';
\$CFG->prefix    = 'mdl_';
\$CFG->dboptions = ['dbpersist' => 0, 'dbport' => '', 'dbsocket' => ''$dbextra];

$wwwrootcfg
\$CFG->dataroot  = '/var/www/moodledata';
\$CFG->admin     = 'admin';
\$CFG->directorypermissions = 0777;
\$CFG->pathtophp = '/usr/local/bin/php';

\$CFG->smtphosts = 'mailhog:1025';
\$CFG->noreplyaddress = 'noreply@example.com';

\$CFG->debug = E_ALL;
\$CFG->debugdisplay = 1;

\$CFG->phpunit_prefix = 'phpu_';
\$CFG->phpunit_dataroot = '/var/www/phpunitdata';

\$CFG->behat_prefix = 'bht_';
\$CFG->behat_dataroot = '/var/www/behatdata';
\$CFG->behat_wwwroot = 'http://$name';
\$CFG->behat_faildump_path = '/var/www/behatfaildumps';
\$CFG->behat_profiles = ['default' => ['browser' => 'chrome', 'wd_host' => 'http://selenium:4444/wd/hub']];

require_once(__DIR__ . '/lib/setup.php');
EOF
fi

if [ "$dbtype" = pgsql ]; then
    tables=$(docker compose -f "$compose" exec -T db psql -U moodle -d moodle -tAc "select count(*) from pg_tables where schemaname='public'") || tables=0
else
    tables=$(docker compose -f "$compose" exec -T db mysql -umoodle -p"$DBPASS" -N -e "select count(*) from information_schema.tables where table_schema='moodle'") || tables=0
fi
tables=$(printf '%s' "$tables" | tr -dc '0-9'); tables=${tables:-0}
if [ "$tables" -gt 0 ]; then
    echo "== database already has $tables tables, install skipped"
else
    echo "== installing database"
    docker compose -f "$compose" exec -T app php admin/cli/install_database.php \
        --lang=en --adminuser=admin --adminpass="$ADMINPASS" --adminemail=admin@example.com \
        --fullname="Moodle $ver" --shortname="$name" --agree-license
fi

if [ "$init_phpunit$init_behat" != 00 ]; then
    docker compose -f "$compose" exec -T app git config --global --add safe.directory /var/www/html
fi
if [ "$init_phpunit" = 1 ]; then
    echo "== phpunit init"
    docker compose -f "$compose" exec -T app php "${web}admin/tool/phpunit/cli/init.php" --no-composer-self-update
fi
if [ "$init_behat" = 1 ]; then
    echo "== behat init"
    docker compose -f "$compose" exec -T app php "${web}admin/tool/behat/cli/init.php"
fi

if [ "$https" = 1 ]; then
    echo "== tailscale serve $tlsport -> 127.0.0.1:$webport"
    tailscale serve --bg --https="$tlsport" "http://127.0.0.1:$webport" >/dev/null
fi

cat <<EOF

== ready: Moodle $ver ($name)
Site:       $wwwroot   admin / $ADMINPASS
${tlsroot:+TLS:        $tlsroot   (tailscale serve, tailnet only)
}            Browsers resolve *.localhost automatically. From curl/CLI (or a browser that does not),
            use  curl -H 'Host: $name.localhost' http://localhost/  or add '127.0.0.1 $name.localhost' to your hosts file.
Port:       $webport (direct to this app; redirects to the site URL above)
Code:       $code   ($branch, PHP $php)
DB:         $dbimage on localhost:$dbport   moodle / $DBPASS
Mail:       http://localhost:8025   (smtp mailhog:1025)
Selenium:   http://localhost:4444   (behat wwwroot http://$name)
Containers: $name-app-1, $name-db-1
Manage:     docker compose -f $compose {up -d | down | down -v}
EOF
